#! /usr/bin/env python
from optparse import OptionParser


if __name__ == '__main__':
    from libodds import App


    parser   = OptionParser()
    parser.add_option("-s", "--time", dest="time", help='Words per minute.',
                      metavar="integer", default=100)

    parser.add_option("-l", "--lang", dest="lang", help='The language..',
                      metavar="string", default='en')

    parser.add_option("-f", "--filename", dest="filename", help='Filename for FIFO file.',
                      metavar="string", default='log.fifo')


    (opt, args) = parser.parse_args()
    print opt.filename
    app = App(opt.lang, opt.filename, opt.time)
    app.run()




